# Generated by Django 5.2.4 on 2025-08-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.CharField(max_length=50)),
                ('login_password', models.CharField(max_length=50)),
            ],
        ),
    ]
